### ISSUE TITLE
Only finds extensions if loaded last

### ISSUE THREAD

**Issue by rgnkn** [keyvchan/telescope-find-pickers.nvim#5]
This plugin only finds extensions if it was loaded last. So, this will find `luasnip`:

```
                require("telescope").load_extension("luasnip")
                require("telescope").load_extension("find_pickers")
```

This one won't:

```
                require("telescope").load_extension("find_pickers")
                require("telescope").load_extension("luasnip")
```

It would be nice if this would be handled correctly or - if not possible / viable - that it gets mentioned on your `README.md`.

[EDIT]

I don't use your keymapping due to some inconveniences.

**Comment by chenkeyv** [comment]
@rgnkn I've been looking into the source code of telescope and didn't found much. I will take a closer look when I have free time. So, stay tone.

Key mapping is a very personal setup, you can use whatever as your convenience. I should probably mention that in README.😄

**Comment by rgnkn** [comment]
Maybe you should mention this in the mean time. 

Rationale:
I tend to write everything in alphabetical order, therefore, your extension was with my first implementation the second `load_extension()` (just after `file_browser`). This lead me to the impression that you're plugin doesn't work (I searched for the mentioned `luasnip`). It was pure luck that I spotted later on the `file_browser` in the list and started playing around. If I wouldn't have spotted the other extension your otherwise excellent plugin would have been disregarded as I normally don't spend more then 5 minutes for checking out new plugins.

**Comment by chenkeyv** [comment]
@rgnkn Thanks for the input 👍. I just got a idea which may fix this, I will try it out later.
