### ISSUE TITLE
typo in README.md

### ISSUE THREAD

**Issue by rgnkn** [keyvchan/telescope-find-pickers.nvim#6]
On your `README.md` you have this:

```
require('telescope').load_extension('find-pickers')
```

But it should be like this (`underscore`):

```
require('telescope').load_extension('find_pickers')
```

**Comment by chenkeyv** [comment]
@rgnkn Thanks for spotting.  It was copied form an early version of my configs, never pay attention to afterwards. 🤣🤣🤣
